# 監視対象の商品リスト（dusedo/d_kaitori_check 参照）
# name: CSV・UI に表示する正式名称
# keywords: 各サイトの検索・照合に使うキーワードリスト

PRODUCTS = {
    'ゲーム': [
        {'name': 'Switch2 国内版マリカーセット',          'keywords': ['マリオカート ワールドセット', 'Nintendo Switch 2 マリオカート', 'Mario Kart World Set']},
        {'name': 'Switch2 国内版',                      'keywords': ['国内専用', 'Switch 2 日本語', 'スイッチ2 国内', 'Switch 2 国内版']},
        {'name': 'Switch2 多言語版',                    'keywords': ['Nintendo Switch 2 多言語', 'Switch 2 多言語']},
        {'name': 'Switch2 Proコン',                    'keywords': ['Nintendo Switch 2 Pro', 'Switch2 Proコン', 'Switch 2 Proコン']},
        {'name': 'Switch 有機白',                      'keywords': ['ELモデル) ホワイト', '有機EL ホワイト', 'OLED White']},
        {'name': 'Switch 有機ネオン',                   'keywords': ['ELモデル) ネオン', '有機EL ネオン', 'OLED Neon']},
        {'name': 'Switch 新型ネオン',                   'keywords': ['バッテリー強化版 ネオン', 'Switch 新型 ネオン', 'Switch V2 Neon']},
        {'name': 'Switch 新型グレー',                   'keywords': ['バッテリー強化版 グレー', 'Switch 新型 グレー', 'Switch V2 Gray']},
        {'name': 'Switch Liteグレー',                  'keywords': ['Switch Lite グレー', 'Switch Lite Gray']},
        {'name': 'Switch Liteブルー',                  'keywords': ['Switch Lite ブルー', 'Switch Lite Blue']},
        {'name': 'Switch Liteコーラル',                 'keywords': ['Switch Lite コーラル', 'Switch Lite Coral']},
        {'name': 'Switch Liteターコイズ',               'keywords': ['Switch Lite ターコイズ', 'Switch Lite Turquoise']},
        {'name': 'Switch Liteイエロー',                 'keywords': ['Switch Lite イエロー', 'Switch Lite Yellow']},
        {'name': 'PlayStation5 Pro',                   'keywords': ['CFI-7000B01', 'PlayStation5 Pro', 'PS5 Pro']},
        {'name': 'PlayStation5',                       'keywords': ['CFI-2000A01', 'Slim Disc']},
        {'name': 'PlayStation5 デジタルエディション',  'keywords': ['CFI-2000B01', 'Slim Digital']},
        {'name': 'PlayStation5 デジタルエディション 日本語専用', 'keywords': ['CFI-2200B01', '日本語 専用 CFI-2200', 'デジタル・エディション 日本語']},
        {'name': 'PlayStation5 デジタル ダブルパック 日本語専用', 'keywords': ['CFIJ-10032', 'ダブルパック 日本語専用']},
        {'name': 'PlayStation5 Ghost of Yotei リミテッドエディション', 'keywords': ['CFIJ-10029', 'Ghost of Yotei ゴールド リミテッド']},
        {'name': 'PlayStation VR2 Horizon同梱版',       'keywords': ['Horizon Call of the Mountain', 'VR2 Horizon Call', 'PS VR2 Horizon', 'PSVR2 Horizon']},
        {'name': 'PlayStation VR2',                    'keywords': ['PS VR2', 'PlayStation VR2', 'PSVR2']},
        {'name': 'リモートプレーヤー',                   'keywords': ['PlayStation Portal', 'リモートプレーヤー', 'Remote Player']},
        {'name': 'Xbox X 1TB ホワイト',                'keywords': ['Xbox Series X 1TB', 'EP2-00708']},
        {'name': 'Xbox S 1TB ホワイト',                'keywords': ['Xbox Series S 1TB ホワイト', 'Xbox Series S 1TB White', 'EP2-00650']},
        {'name': 'Xbox X',                             'keywords': ['Xbox Series X']},
        {'name': 'Xbox S',                             'keywords': ['Xbox Series S']},
        {'name': 'Meta Quest 3 512',                   'keywords': ['Meta Quest 3 512GB', 'Meta Quest 3 512', 'MetaQuest 3 512', 'Quest 3 512GB']},
        {'name': 'Meta Quest 3 128',                   'keywords': ['Meta Quest 3 128GB', 'Meta Quest 3 128', 'MetaQuest 3 128', 'Quest 3 128GB']},
        {'name': 'Meta Quest 3S 128GB',                'keywords': ['Meta Quest 3S 128GB', 'Meta Quest 3S 128', 'MetaQuest 3S 128']},
        {'name': 'Meta Quest 3S 256GB',                'keywords': ['Meta Quest 3S 256GB', 'Meta Quest 3S 256', 'MetaQuest 3S 256']},
        {'name': 'Pokemon GO Plus+',                   'keywords': ['Pokemon GO Plus', 'ポケモンGOプラス']},
        {'name': 'Steam Deck 有機EL 1TB',              'keywords': ['Steam Deck 有機EL 1TB', 'Steam Deck OLED 1TB']},
        {'name': 'Steam Deck 有機EL 512GB',            'keywords': ['Steam Deck 有機EL 512', 'Steam Deck OLED 512GB']},
        {'name': 'Alarmo',                             'keywords': ['Alarmo', 'ニンテンドーサウンドクロック']},
        {'name': 'PlayStation5 ディスクドライブ',     'keywords': ['CFI-ZDD1J', 'PS5 ディスクドライブ  CFI']},
        {'name': 'DualSense Spider-Man 2',          'keywords': ['CFI-ZCT1JZ2']},
        {'name': 'DualSense 30周年',                'keywords': ['CFI-ZCT1J30']},
        {'name': 'DualSense ロボット',               'keywords': ['CFI-ZCT1JZ3']},
        {'name': 'DualSense FINAL FANTASY',          'keywords': ['CFIJ-15500']},
        {'name': 'DualSense ゴッド・オブ・ウォー',   'keywords': ['CFI-ZCT1JZ1']},
        {'name': 'DualSense フォートナイ',            'keywords': ['CFI-ZCT1JZ4']},
        {'name': 'DualSense Ghost of Yotei ゴールド','keywords': ['CFI-ZCT1JZ7']},
        {'name': 'DualSense Ghost of Yotei ブラック','keywords': ['CFI-ZCT1JZ8']},
        {'name': 'DualSense ゴッド・オブ・ウォー 20th','keywords': ['CFI-ZCT1JZA']},
        {'name': 'DualSense ミッドナイト ブラック USB','keywords': ['CFIJ15502']},
        {'name': 'DualSense モンスターハンターワイルズ','keywords': ['CFI-ZCT1JZ5']},
        {'name': 'DualSense Marathon',               'keywords': ['CFI-ZCT1JZD']},
        {'name': 'DualSense アストロボット',          'keywords': ['CFI-ZCT1JZC']},
        {'name': 'DualSense 原神',                   'keywords': ['CFI-ZCT2JZE']},
        {'name': 'DualSense テクノ レッド',           'keywords': ['CFI-ZCT2J13']},
        {'name': 'DualSense リミックス グリーン',     'keywords': ['CFI-ZCT2J14']},
        {'name': 'DualSense リズム ブルー',           'keywords': ['CFI-ZCT2J15']},
        {'name': 'DualSense クロマ パール',           'keywords': ['CFI-ZCT1J12']},
        {'name': 'DualSense インディゴ',              'keywords': ['CFI-ZCT1J11']},
        {'name': 'DualSense クロマ グリーン',         'keywords': ['CFI-ZCT1J10']},
        {'name': 'DualSense コバルト ブルー',         'keywords': ['CFI-ZCT1J09']},
        {'name': 'DualSense シルバー',                'keywords': ['CFI-ZCT1J08']},
        {'name': 'DualSense ヴォルカニック レッド',   'keywords': ['CFI-ZCT1J07']},
        {'name': 'DualSense グレー カモフラージュ',   'keywords': ['CFI-ZCT1J06']},
        {'name': 'DualSense ブルー',                  'keywords': ['CFI-ZCT1J05']},
        {'name': 'DualSense パープル',                'keywords': ['CFI-ZCT1J04']},
        {'name': 'DualSense ピンク',                  'keywords': ['CFI-ZCT1J03']},
        {'name': 'DualSense レッド',                  'keywords': ['CFI-ZCT1J02']},
        {'name': 'DualSense ブラック',                'keywords': ['CFI-ZCT1J01']},
        {'name': 'DualSense ホワイト',                'keywords': ['PS5 コントローラー ホワイト CFI-ZCT1J', 'CFI-ZCT1J ']},
        {'name': 'Switch Proコン ゼルダ',             'keywords': ['Proコントローラー ゼルダの伝説', 'Switch Proコントローラー ゼルダ']},
        {'name': 'Switch Proコン スプラ3',            'keywords': ['Proコントローラー スプラトゥーン3', 'スプラトゥーン3エディション']},
        {'name': 'Switch Proコン',                    'keywords': ['Nintendo Switch Proコントローラー']},
        {'name': 'Joy-Con 2 ブルー/レッドセット',     'keywords': ['Joy-Con 2 (L) ライトブルー/(R) ライトレッド']},
        {'name': 'Joy-Con 2 パープル/グリーンセット', 'keywords': ['Joy-Con 2 (L) ライトパープル/(R) ライトグリーン']},
        {'name': 'Joy-Con 2 L ライトブルー',          'keywords': ['Joy-Con 2 (L) ライトブルー']},
        {'name': 'Joy-Con 2 R ライトレッド',          'keywords': ['Joy-Con 2 (R) ライトレッド']},
        {'name': 'Joy-Con 2 充電グリップ',            'keywords': ['Joy-Con 2 充電グリップ']},
        {'name': 'Joy-Con マリパ4人セット',           'keywords': ['マリオパーティ 4人で遊べる Joy-Conセット']},
        {'name': 'Joy-Con マリパセット',              'keywords': ['マリオパーティ  Joy-Conセット', 'マリオパーティ Joy-Conセット']},
        {'name': 'Joy-Con ネオンレッド/ネオンブルー', 'keywords': ['ネオンレッド/ネオンブルー']},
        {'name': 'Joy-Con ネオングリーン/ネオンピンク','keywords': ['ネオングリーン/ネオンピンク']},
        {'name': 'Joy-Con ネオンブルー/ネオンイエロー','keywords': ['ネオンブルー/ネオンイエロー']},
        {'name': 'Joy-Con ネオンパープル/ネオンオレンジ','keywords': ['ネオンパープル/ネオンオレンジ']},
        {'name': 'Joy-Con パステルパープル/パステルグリーン','keywords': ['パステルパープル/ パステルグリーン', 'パステルパープル/パステルグリーン']},
        {'name': 'Joy-Con パステルピンク/パステルイエロー','keywords': ['パステルピンク/パステルイエロー']},
        {'name': 'Joy-Con パステルピンク',            'keywords': ['Joy-Con (L)/(R) パステルピンク']},
        {'name': 'Joy-Con グレー/グレー',             'keywords': ['Joy-Con (L)/(R)  グレー', 'Joy-Con グレー/グレー']},
        {'name': 'Joy-Con ネオンイエロー',            'keywords': ['Joy-Con (L)/(R)  ネオンイエロー', 'Joy-Con (L)/(R) ネオンイエロー']},
        {'name': 'Joy-Con レッド',                    'keywords': ['Joy-Con (L)/(R) レッド']},
        # ゲームソフト（Switch 2版を先に置き、キーワード優先マッチさせる）
        # PS5専用（Ghost of Yotei 本体バンドルは上のハードウェアセクションに移動済み）
        {'name': 'PS5 Split Fiction',                      'keywords': ['Split Fiction', 'スプリット フィクション']},
        {'name': 'PS5 It Takes Two',                       'keywords': ['It Takes Two', 'イット テイクス トゥー']},
        {'name': 'PS5 プラグマタ',                         'keywords': ['プラグマタ', 'Pragmata']},
        # Pokemon LEGENDS Z-A（Switch / Switch 2 両対応）
        {'name': 'Pokemon LEGENDS Z-A Switch 2',           'keywords': ['Switch 2 Pokemon LEGENDS Z-A', 'Switch2 Pokemon LEGENDS Z-A', 'Pokemon LEGENDS Z-A Nintendo Switch 2', 'Switch 2 ポケモン LEGENDS Z-A']},
        {'name': 'Pokemon LEGENDS Z-A Switch',             'keywords': ['ポケモン LEGENDS Z-A', 'Pokemon LEGENDS Z-A', 'LEGENDS Z-A']},
        # ゼルダ（Switch）
        {'name': 'ゼルダ ティアーズ オブ ザ キングダム',   'keywords': ['ティアーズ オブ ザ キングダム', 'Tears of the Kingdom', 'ティアキン']},
        {'name': 'ゼルダ 知恵のかりもの',                  'keywords': ['知恵のかりもの', 'Echoes of Wisdom']},
        # リングフィット（Switch）
        {'name': 'リングフィット アドベンチャー',           'keywords': ['リングフィット アドベンチャー', 'リングフィット', 'Ring Fit Adventure']},
        # マリオパーティ（Switch）
        {'name': 'マリオパーティ ジャンボリー',             'keywords': ['マリオパーティ ジャンボリー', 'Mario Party Jamboree', 'スーパー マリオパーティ ジャンボリー']},
        # ゼノブレイドクロス（Switch 2専用）
        {'name': 'ゼノブレイドクロス Switch 2',            'keywords': ['ゼノブレイドクロス', 'Xenoblade Chronicles X', 'ゼノブレイド クロス']},
        # トモダチコレクション（Switch / Switch 2 両対応）
        {'name': 'トモダチコレクション Switch 2',           'keywords': ['Switch 2 トモダチコレクション', 'Switch2 トモダチコレクション', 'トモダチコレクション Nintendo Switch 2']},
        {'name': 'トモダチコレクション Switch',             'keywords': ['トモダチコレクション わくわく', 'Tomodachi Collection', 'トモダチコレクション']},
        # モンスターハンターストーリーズ3（Switch / Switch 2 両対応）
        {'name': 'モンスターハンターストーリーズ3 Switch 2', 'keywords': ['NS2 モンスターハンターストーリーズ3', 'Switch 2 モンスターハンターストーリーズ3']},
        {'name': 'モンスターハンターストーリーズ3 Switch',   'keywords': ['モンスターハンターストーリーズ3', 'Monster Hunter Stories 3']},
        # マリオカート ワールド（Switch 2専用）
        {'name': 'マリオカート ワールド ソフト',            'keywords': ['マリオカート ワールド', 'Mario Kart World']},
    ],
    'カメラ': [
        {'name': 'チェキフィルム 2P',                   'keywords': ['instax フィルム 20枚入', 'JP2', 'mini film 2P', 'チェキ フィルム 2パック']},
        {'name': 'チェキフィルム 1P',                   'keywords': ['instax フィルム 10枚入', 'JP1', 'mini film 1P', 'チェキ フィルム 1パック']},
        {'name': 'instax SQUARE フィルム WW1',          'keywords': ['WW1', 'SQUARE FUJIFILM instax フィルム(10枚入)']},
        {'name': 'instax SQUARE フィルム WW2',          'keywords': ['WW2', 'SQUARE FUJIFILM instax フィルム(20枚入)']},
        {'name': 'instax WIDE フィルム 10枚',           'keywords': ['WIDE FUJIFILM instax フィルム(10枚入)']},
        {'name': 'instax WIDE フィルム 20枚',           'keywords': ['WIDE FUJIFILM instax フィルム(20枚入)']},
        {'name': 'instax WIDE フィルム 50枚',           'keywords': ['WIDE FUJIFILM instax フィルム(50枚入)']},
        {'name': 'instax mini フィルム PASTEL GALAXY',  'keywords': ['PASTEL GALAXY']},
        {'name': '写ルンです（新パッケージ）',             'keywords': ['写ルンです', 'Fujifilm Disposable']},
        {'name': 'instax mini 12 ピンク',               'keywords': ['mini 12 チェキ [ピンク]', 'mini 12 ピンク', 'mini 12 Pink']},
        {'name': 'instax mini 13 ピンク',               'keywords': ['キャンディピンク', 'mini 13 チェキ [キャンディピンク]', 'mini 13 ピンク', 'mini 13 Pink']},
        {'name': 'instax mini 13 ブルー',               'keywords': ['フロストブルー', 'Frost Blue', 'mini 13 チェキ [フロストブルー]', 'mini 13 ブルー', 'mini 13 Blue']},
        {'name': 'instax mini 13 グリーン',             'keywords': ['ラグーングリーン', 'ミントグリーン', 'mini 13 チェキ [ラグーングリーン]', 'mini 13 チェキ [ミントグリーン]', 'mini 13 グリーン', 'mini 13 Green']},
        {'name': 'instax mini 13 ホワイト',             'keywords': ['クレイホワイト', 'クリーミーホワイト', 'mini 13 チェキ [クレイホワイト]', 'mini 13 チェキ [クリーミーホワイト]', 'mini 13 ホワイト', 'mini 13 White']},
        {'name': 'instax mini 13 パープル',             'keywords': ['ドリーミーパープル', 'mini 13 チェキ [ドリーミーパープル]', 'mini 13 パープル', 'mini 13 Purple']},
        {'name': 'instax mini 40',                     'keywords': ['instax mini 40']},
        {'name': 'instax mini 90 黒',                  'keywords': ['ネオクラシック[ブラック]', 'mini 90 ブラック', 'mini 90 Black']},
        {'name': 'instax mini 90 茶',                  'keywords': ['ネオクラシック [ブラウン]', 'ネオクラシック[ブラウン]', 'mini 90 ブラウン', 'mini 90 Brown']},
        {'name': 'instax mini 99',                     'keywords': ['instax mini 99']},
        {'name': 'instax WIDE 400 ブラック',            'keywords': ['ジェットブラック', 'WIDE 400 チェキ [ジェットブラック]', 'WIDE 400 ブラック', 'WIDE400 Black', 'WIDE 400 Black', 'WIDE 400 チェキ [ブラック]']},
        {'name': 'instax WIDE 400 グリーン',            'keywords': ['WIDE 400 グリーン', 'WIDE 400 チェキ [グリーン]', 'WIDE400 Green']},
        {'name': 'instax WIDE 400',                    'keywords': ['WIDE 400 チェキ', 'instax WIDE 400', 'WIDE400']},
        {'name': 'instax mini Evo 黒',                 'keywords': ['Evo チェキ USB [ブラック]', 'mini Evo チェキ USB [ブラック]', 'mini Evo ブラック', 'mini Evo Black']},
        {'name': 'instax mini Evo 茶',                 'keywords': ['Evo チェキ USB [ブラウン]', 'mini Evo チェキ USB [ブラウン]', 'mini Evo ブラウン', 'mini Evo Brown']},
        {'name': 'instax WIDE Evo',                    'keywords': ['WIDE Evo チェキ', 'instax WIDE Evo']},
        {'name': 'instax mini Evo PINK',               'keywords': ['Evo チェキ USB [ピンク]', 'mini Evo チェキ USB [ピンク]', 'mini Evo ピンク', 'mini Evo PINK']},
        {'name': 'instax mini Evo GENTLE ROSE',        'keywords': ['ジェントル ローズ', 'Evo チェキ USB [ジェントル ローズ]', 'GENTLE ROSE', 'ジェントルローズ']},
        {'name': 'instax mini Evo Cinema',             'keywords': ['mini Evo Cinema', 'Evo シネマ']},
        {'name': 'instax SQUARE SQ40 ブラック',         'keywords': ['SQ40 チェキスクエア', 'SQ40 ブラック', 'SQ40 Black']},
        {'name': 'instax SQUARE SQ1 ブルー',           'keywords': ['SQ1 [ブルー]', 'SQ1 ブルー', 'SQ1 Blue']},
        {'name': 'instax SQUARE SQ1 オレンジ',         'keywords': ['SQ1 [オレンジ]', 'SQ1 オレンジ', 'SQ1 Orange']},
        {'name': 'instax SQUARE SQ1 ホワイト',         'keywords': ['SQ1 [ホワイト]', 'SQ1 ホワイト', 'SQ1 White']},
        {'name': 'IXY 650 m シルバー',                 'keywords': ['IXY 650 m [シルバー]', 'IXY 650 m シルバー', '650 m [シルバー]']},
        {'name': 'IXY 650 m ブラック',                 'keywords': ['IXY 650 m [ブラック]', 'IXY 650 m ブラック', '650 m [ブラック]']},
        {'name': 'IXY 650 シルバー',                   'keywords': ['IXY 650 [シルバー]', 'IXY 650 シルバー']},
        {'name': 'IXY 650 ブラック',                   'keywords': ['IXY 650 [ブラック]', 'IXY 650 ブラック']},
        {'name': 'SX740 シルバー',                     'keywords': ['SX740 HS [シルバー]', 'SX740 シルバー', 'SX740 Silver']},
        {'name': 'SX740 ブラック',                     'keywords': ['SX740 HS [ブラック]', 'SX740 ブラック', 'SX740 Black']},
        {'name': 'SX70',                               'keywords': ['SX70', 'PowerShot SX70']},
        {'name': 'PowerShot V10',                      'keywords': ['PowerShot V10', 'Canon V10']},
        {'name': 'PowerShot V1',                       'keywords': ['PowerShot V1 ', 'Canon V1 ']},
        {'name': 'G7X Mark III 30th Anniversary',      'keywords': ['30th Anniversary Edition', 'G7 X Mark III 30th']},
        {'name': 'G7 X Mark III シルバー',             'keywords': ['G7 X Mark III　SV', 'G7 X Mark III SV', 'Mark III シルバー']},
        {'name': 'G7 X Mark III ブラック',              'keywords': ['G7 X Mark III　B', 'G7 X Mark III B', 'Mark III ブラック', 'G7 X Mark III']},
        {'name': 'G7 X Mark II',                       'keywords': ['G7 X MarkII', 'G7X Mark2', 'PowerShot G7 X Mark II']},
        {'name': 'PowerShot G1 X Mark III',            'keywords': ['G1 X Mark III', 'PowerShot G1 X']},
        {'name': 'X100VI シルバー（新）',               'keywords': ['X100VI Silver', 'X100VI Silver 【新型']},
        {'name': 'X100VI ブラック（新）',               'keywords': ['X100VI Black', 'X100VI Black 【新型']},
        {'name': 'X100VI シルバー（旧）',               'keywords': ['X100VI [シルバー]', 'fujifilm x100vi [シルバー]']},
        {'name': 'X100VI ブラック（旧）',               'keywords': ['X100VI [ブラック]']},
        {'name': 'X-T30 レンズキット',                  'keywords': ['X-T30', 'Fujifilm X-T30 Lens Kit']},
        {'name': 'LUMIX DC-TZ99 ブラック',             'keywords': ['LUMIX TZ99 Black', 'DC-TZ99-K', 'TZ99 ブラック']},
        {'name': 'LUMIX DC-TZ99 ホワイト',             'keywords': ['LUMIX TZ99 White', 'DC-TZ99-W', 'TZ99 ホワイト']},
        {'name': 'RICOH GR IV Monochrome',             'keywords': ['GR IV Monochrome', 'GR4 Monochrome']},
        {'name': 'RICOH GR IV',                        'keywords': ['RICOH GR IV', 'GR4', 'GR IV']},
        {'name': 'RICOH GR IIIx Urban Edition',        'keywords': ['GR IIIx Urban', 'GR3x Urban']},
        {'name': 'RICOH GR III Diary Edition',         'keywords': ['GR III Diary', 'GR3 Diary']},
        {'name': 'RICOH GR IIIx',                     'keywords': ['RICOH GR IIIx', 'GR3x', 'GR IIIx']},
        {'name': 'RICOH GR III',                       'keywords': ['RICOH GR III', 'GR3', 'GR III']},
        {'name': 'Nikon Z50II ダブルズームキット',        'keywords': ['Z50II ダブルズーム', 'Z50II Double Zoom']},
        {'name': 'Nikon Z50II 18-140 VRキット',        'keywords': ['Z50II 18-140']},
        {'name': 'Nikon Z50II 16-50 VRキット',        'keywords': ['Z50II 16-50']},
        {'name': 'Nikon Z50II ボディ',                 'keywords': ['Nikon Z50II', 'Z50II', 'Z50 II']},
        # タムロン レンズ
        {'name': 'Tamron 18-300 ニコンZ',             'keywords': ['B061) ニコンZ用', 'B061 ニコンZ', 'タムロン 18-300 ニコン']},
        {'name': 'Tamron 18-300 フジ',                'keywords': ['B061) [フジフイルム用]', 'タムロン 18-300 フジ']},
        {'name': 'Tamron 18-300 ソニーE',             'keywords': ['B061) [ソニーE用]', 'タムロン 18-300 ソニー', 'TAMRON 18-300mm F/3.5-6.3']},
        {'name': 'Tamron 28-75 G2 ニコンZ',           'keywords': ['A063) [ニコンZ用]', 'A063 ニコンZ', 'TAMRON 28-75 ニコン']},
        {'name': 'Tamron 28-75 G2 ソニーE',           'keywords': ['A063S', 'TAMRON 28-75mm F/2.8']},
        {'name': 'Tamron 28-300',                     'keywords': ['A074', 'TAMRON 28-300']},
        {'name': 'Tamron 28-200',                     'keywords': ['A071', 'TAMRON 28-200']},
        {'name': 'Tamron 25-200',                     'keywords': ['A079', 'TAMRON 25-200', 'タムロン 25-200']},
        # その他レンズ・カメラ
        {'name': 'NIKKOR Z DX 50-250mm',              'keywords': ['NIKKOR Z DX 50-250', 'Z DX 50-250']},
        {'name': 'OM SYSTEM PEN E-P7',                'keywords': ['PEN E-P7', 'OM SYSTEM E-P7', 'E-P7']},
        {'name': 'Sigma 28-70mm F2.8',                'keywords': ['SIGMA 28-70', 'シグマ 28-70']},
    ],
    'ポケカ': [
        {'name': 'ニンジャスピナー',      'keywords': ['ニンジャスピナー', 'Ninja Spinner']},
        {'name': 'ムニキスゼロ',          'keywords': ['ムニキスゼロ']},
        {'name': 'MEGAドリームex',        'keywords': ['MEGAドリーム', 'Mega Dream ex']},
        {'name': 'インフェルノX',         'keywords': ['インフェルノX', 'Inferno X']},
        {'name': 'メガブレイブ',          'keywords': ['メガブレイブ', 'Mega Brave']},
        {'name': 'メガシンフォニア',      'keywords': ['メガシンフォニア', 'Mega Sinfonia']},
        {'name': 'ブラックボルト',        'keywords': ['ブラックボルト', 'Black Bolt']},
        {'name': 'ホワイトフレア',        'keywords': ['ホワイトフレア', 'White Flare']},

        {'name': 'ロケット団の栄光',      'keywords': ['ロケット団の栄光', 'Team Rocket Glory']},
        {'name': '熱風のアリーナ',        'keywords': ['熱風のアリーナ']},
        {'name': 'バトルパートナーズ',    'keywords': ['バトルパートナーズ', 'Battle Partners']},
        {'name': 'テラスタルフェスex',    'keywords': ['テラスタルフェス', 'Terastal Fes']},
        {'name': '超電ブレイカー',        'keywords': ['超電ブレイカー', 'Surging Sparks']},
        {'name': '楽園ドラゴーナ',        'keywords': ['楽園ドラゴーナ', 'Paradise Dragona']},
        {'name': 'ステラミラクル',        'keywords': ['ステラミラクル', 'Stellar Miracle']},
        {'name': 'ナイトワンダラー',      'keywords': ['ナイトワンダラー', 'Night Wanderer']},
        {'name': '変幻の仮面',            'keywords': ['変幻の仮面', 'Twilight Masquerade']},
        {'name': 'クリムゾンヘイズ',      'keywords': ['クリムゾンヘイズ', 'Crimson Haze']},
        {'name': 'ワイルドフォース',      'keywords': ['ワイルドフォース', 'Wild Force']},
        {'name': 'サイバージャッジ',      'keywords': ['サイバージャッジ', 'Cyber Judge']},
        {'name': 'シャイニートレジャーex','keywords': ['シャイニートレジャー', 'Shiny Treasure']},
        {'name': '古代の咆哮',            'keywords': ['古代の咆哮', 'Ancient Roar']},
        {'name': '未来の一閃',            'keywords': ['未来の一閃', 'Future Flash']},
        {'name': 'レイジングサーフ',      'keywords': ['レイジングサーフ', 'Raging Surf']},
        {'name': '黒炎の支配者',          'keywords': ['黒炎の支配者', 'Obsidian Flames']},
        {'name': 'ポケモンカード151',     'keywords': ['ポケモンカード151', 'Pokemon 151']},
        {'name': 'VSTARユニバース',       'keywords': ['VSTARユニバース', 'VSTAR Universe']},
        {'name': 'クレイバースト',        'keywords': ['クレイバースト', 'Paldea Evolved']},
        {'name': 'スノーハザード',        'keywords': ['スノーハザード', 'Snow Hazard']},
        {'name': 'トリプレットビート',    'keywords': ['トリプレットビート', 'Triplet Beat']},
        {'name': 'スカーレットex',        'keywords': ['スカーレットex', 'Scarlet ex']},
        {'name': 'バイオレットex',        'keywords': ['バイオレットex', 'Violet ex']},
    ],
    'ワンピ': [
        {'name': 'OP-10 王族の血統',      'keywords': ['OP-10', '王族の血統', 'Royal Blood']},
        {'name': 'OP-11 神速の拳',        'keywords': ['OP-11', '神速の拳']},
        {'name': 'OP-12 師弟の絆',        'keywords': ['OP-12', '師弟の絆']},
        {'name': 'OP-13 受け継がれる意志', 'keywords': ['OP-13', '受け継がれる意志']},
        {'name': 'OP-14 蒼海の七傑',      'keywords': ['OP-14', '蒼海の七傑']},
        {'name': 'OP-15 神の島の冒険',    'keywords': ['OP-15', '神の島の冒険']},
        {'name': 'EB-03 Heroines Edition', 'keywords': ['EB-03', 'Heroines Edition']},
        {'name': 'EB-04 EGGHEAD CRISIS',   'keywords': ['EB-04', 'EGGHEAD CRISIS']},
        {'name': 'PRB-01 THE BEST',        'keywords': ['PRB-01']},
        {'name': 'PRB-02 THE BEST vol.2',  'keywords': ['PRB-02', 'THE BEST vol.2']},
    ],
    'スマートフォン': [
        # iPhone 17 Pro Max（色別 × 容量別）
        {'name': 'iPhone 17 Pro Max 256GB シルバー',         'keywords': ['iPhone 17 Pro Max 256GB シルバー', 'iPhone 17 Pro Max 256 Silver', 'Pro Max 256 シルバー']},
        {'name': 'iPhone 17 Pro Max 256GB ディープブルー',   'keywords': ['iPhone 17 Pro Max 256GB ディープブルー', 'iPhone 17 Pro Max 256 Blue', 'Pro Max 256 ディープブルー', 'Pro Max 256 Deep Blue']},
        {'name': 'iPhone 17 Pro Max 256GB コズミックオレンジ','keywords': ['iPhone 17 Pro Max 256GB コズミックオレンジ', 'iPhone 17 Pro Max 256 Orange', 'Pro Max 256 コズミックオレンジ', 'Pro Max 256 Cosmic Orange']},
        {'name': 'iPhone 17 Pro Max 512GB シルバー',         'keywords': ['iPhone 17 Pro Max 512GB シルバー', 'iPhone 17 Pro Max 512 Silver', 'Pro Max 512 シルバー']},
        {'name': 'iPhone 17 Pro Max 512GB ディープブルー',   'keywords': ['iPhone 17 Pro Max 512GB ディープブルー', 'iPhone 17 Pro Max 512 Blue', 'Pro Max 512 ディープブルー', 'Pro Max 512 Deep Blue']},
        {'name': 'iPhone 17 Pro Max 512GB コズミックオレンジ','keywords': ['iPhone 17 Pro Max 512GB コズミックオレンジ', 'iPhone 17 Pro Max 512 Orange', 'Pro Max 512 コズミックオレンジ', 'Pro Max 512 Cosmic Orange']},
        {'name': 'iPhone 17 Pro Max 1TB シルバー',           'keywords': ['iPhone 17 Pro Max 1TB シルバー', 'iPhone 17 Pro Max 1TB Silver', 'Pro Max 1TB シルバー']},
        {'name': 'iPhone 17 Pro Max 1TB ディープブルー',     'keywords': ['iPhone 17 Pro Max 1TB ディープブルー', 'iPhone 17 Pro Max 1TB Blue', 'Pro Max 1TB ディープブルー', 'Pro Max 1TB Deep Blue']},
        {'name': 'iPhone 17 Pro Max 1TB コズミックオレンジ', 'keywords': ['iPhone 17 Pro Max 1TB コズミックオレンジ', 'iPhone 17 Pro Max 1TB Orange', 'Pro Max 1TB コズミックオレンジ', 'Pro Max 1TB Cosmic Orange']},
        {'name': 'iPhone 17 Pro Max 2TB シルバー',           'keywords': ['iPhone 17 Pro Max 2TB シルバー', 'iPhone 17 Pro Max 2TB Silver', 'Pro Max 2TB シルバー']},
        {'name': 'iPhone 17 Pro Max 2TB ディープブルー',     'keywords': ['iPhone 17 Pro Max 2TB ディープブルー', 'iPhone 17 Pro Max 2TB Blue', 'Pro Max 2TB ディープブルー', 'Pro Max 2TB Deep Blue']},
        {'name': 'iPhone 17 Pro Max 2TB コズミックオレンジ', 'keywords': ['iPhone 17 Pro Max 2TB コズミックオレンジ', 'iPhone 17 Pro Max 2TB Orange', 'Pro Max 2TB コズミックオレンジ', 'Pro Max 2TB Cosmic Orange']},
        # iPhone 17 Pro（色別 × 容量別）
        {'name': 'iPhone 17 Pro 256GB シルバー',             'keywords': ['iPhone 17 Pro 256GB シルバー', 'iPhone 17 Pro 256 Silver', 'Pro 256 シルバー']},
        {'name': 'iPhone 17 Pro 256GB ディープブルー',       'keywords': ['iPhone 17 Pro 256GB ディープブルー', 'iPhone 17 Pro 256 Blue', 'Pro 256 ディープブルー', 'Pro 256 Deep Blue']},
        {'name': 'iPhone 17 Pro 256GB コズミックオレンジ',   'keywords': ['iPhone 17 Pro 256GB コズミックオレンジ', 'iPhone 17 Pro 256 Orange', 'Pro 256 コズミックオレンジ', 'Pro 256 Cosmic Orange']},
        {'name': 'iPhone 17 Pro 512GB シルバー',             'keywords': ['iPhone 17 Pro 512GB シルバー', 'iPhone 17 Pro 512 Silver', 'Pro 512 シルバー']},
        {'name': 'iPhone 17 Pro 512GB ディープブルー',       'keywords': ['iPhone 17 Pro 512GB ディープブルー', 'iPhone 17 Pro 512 Blue', 'Pro 512 ディープブルー', 'Pro 512 Deep Blue']},
        {'name': 'iPhone 17 Pro 512GB コズミックオレンジ',   'keywords': ['iPhone 17 Pro 512GB コズミックオレンジ', 'iPhone 17 Pro 512 Orange', 'Pro 512 コズミックオレンジ', 'Pro 512 Cosmic Orange']},
        {'name': 'iPhone 17 Pro 1TB シルバー',               'keywords': ['iPhone 17 Pro 1TB シルバー', 'iPhone 17 Pro 1TB Silver', 'Pro 1TB シルバー']},
        {'name': 'iPhone 17 Pro 1TB ディープブルー',         'keywords': ['iPhone 17 Pro 1TB ディープブルー', 'iPhone 17 Pro 1TB Blue', 'Pro 1TB ディープブルー', 'Pro 1TB Deep Blue']},
        {'name': 'iPhone 17 Pro 1TB コズミックオレンジ',     'keywords': ['iPhone 17 Pro 1TB コズミックオレンジ', 'iPhone 17 Pro 1TB Orange', 'Pro 1TB コズミックオレンジ', 'Pro 1TB Cosmic Orange']},
    ],
    'その他': [
        {'name': 'Tamagotchi Paradise Purple Sky', 'keywords': ['Paradise - Purple Sky', 'Tamagotchi Paradise Purple']},
        {'name': 'Tamagotchi Paradise Blue Water',  'keywords': ['Paradise - Blue Water', 'Tamagotchi Paradise Blue']},
        {'name': 'Tamagotchi Paradise Pink Land',   'keywords': ['Paradise - Pink Land', 'Tamagotchi Paradise Pink']},
        {'name': 'Tamagotchi Paradise Jade Forest', 'keywords': ['Paradise - Jade Forest', 'Tamagotchi Paradise Jade']},
    ],
}

# フラットなリスト（全商品）
ALL_PRODUCTS = []
for category, items in PRODUCTS.items():
    for item in items:
        ALL_PRODUCTS.append({**item, 'category': category})

# 商品名のセット（重複除去用）
PRODUCT_NAMES = {p['name'] for p in ALL_PRODUCTS}
