# 監視対象の商品リスト（dusedo/d_kaitori_check 参照）
# name: CSV・UI に表示する正式名称
# keywords: 各サイトの検索・照合に使うキーワードリスト

PRODUCTS = {
    'ゲーム': [
        {'name': 'Nintendo Switch 2 マリオカート ワールドセット 日本語・国内専用',          'keywords': ['マリオカート ワールドセット', 'Nintendo Switch 2 マリオカート', 'Mario Kart World Set']},
        {'name': 'Nintendo Switch 2 日本語・国内専用',                      'keywords': ['国内専用', 'Switch 2 日本語', 'スイッチ2 国内', 'Switch 2 国内版']},
        {'name': 'Nintendo Switch 2 多言語版',                    'keywords': ['Nintendo Switch 2 多言語', 'Switch 2 多言語']},
        {'name': 'Nintendo Switch 2 Proコントローラー',                    'jan': '4902370552843', 'keywords': ['Nintendo Switch 2 Proコントローラー', 'Nintendo Switch 2 Pro', 'Switch2 Proコン', 'Switch 2 Proコン']},
        {'name': 'Nintendo Switch (有機ELモデル) ホワイト',                      'keywords': ['ELモデル) ホワイト', '有機EL ホワイト', 'OLED White']},
        {'name': 'Nintendo Switch (有機ELモデル) ネオンブルー・ネオンレッド',                   'keywords': ['ELモデル) ネオン', '有機EL ネオン', 'OLED Neon']},
        {'name': 'Nintendo Switch 新型 バッテリー強化版 ネオンブルー/(R) ネオンレッド',                   'keywords': ['バッテリー強化版 ネオン', 'Switch 新型 ネオン', 'Switch V2 Neon']},
        {'name': 'Nintendo Switch 新型 バッテリー強化版 グレー',                   'keywords': ['バッテリー強化版 グレー', 'Switch 新型 グレー', 'Switch V2 Gray']},
        {'name': 'Nintendo Switch Lite グレー',                  'keywords': ['Switch Lite グレー', 'Switch Lite Gray']},
        {'name': 'Nintendo Switch Lite ブルー',                  'keywords': ['Switch Lite ブルー', 'Switch Lite Blue']},
        {'name': 'Nintendo Switch Lite コーラル',                 'keywords': ['Switch Lite コーラル', 'Switch Lite Coral']},
        {'name': 'Nintendo Switch Lite ターコイズ',               'keywords': ['Switch Lite ターコイズ', 'Switch Lite Turquoise']},
        {'name': 'Nintendo Switch Lite イエロー',                 'keywords': ['Switch Lite イエロー', 'Switch Lite Yellow']},
        {'name': 'PlayStation5 Pro CFI-7000B01',                   'keywords': ['CFI-7000B01', 'PlayStation5 Pro', 'PS5 Pro']},
        {'name': 'PlayStation5 Slim Disc CFI-2000A01',                       'keywords': ['CFI-2000A01', 'Slim Disc']},
        {'name': 'PlayStation5 Slim Digital エディション CFI-2000B01',  'keywords': ['CFI-2000B01', 'Slim Digital']},
        {'name': 'PlayStation 5 デジタル ・ エディション 日本語 専用 CFI-2200B01', 'keywords': ['CFI-2200B01', '日本語 専用 CFI-2200', 'デジタル・エディション 日本語']},
        {'name': 'PlayStation 5 デジタルED ダブルパック 日本語専用 CFIJ-10032', 'keywords': ['CFIJ-10032', 'ダブルパック 日本語専用']},
        {'name': 'PlayStation(R)5 ”Ghost of Yotei” ゴールド リミテッドエディション CFIJ-10029', 'keywords': ['CFIJ-10029', 'Ghost of Yotei ゴールド リミテッド']},
        {'name': 'PlayStation VR2 “Horizon Call of the Mountain” 同梱版 CFIJ-17001',       'keywords': ['Horizon Call of the Mountain', 'VR2 Horizon Call', 'PS VR2 Horizon', 'PSVR2 Horizon']},
        {'name': 'PlayStation VR2 CFIJ-17000',                    'keywords': ['PS VR2', 'PlayStation VR2', 'PSVR2']},
        {'name': 'PlayStation Portal リモートプレーヤー CFIJ-18000',                   'keywords': ['PlayStation Portal', 'リモートプレーヤー', 'Remote Player']},
        {'name': 'PlayStation Portal リモートプレーヤー ブラック CFIJ-18001', 'jan': '4948872017251', 'keywords': ['CFIJ-18001', 'PlayStation Portal ブラック', 'リモートプレーヤー ブラック']},
        {'name': 'Xbox Series X 1TB デジタル エディション ホワイト EP2-00708',                'keywords': ['Xbox Series X 1TB', 'EP2-00708']},
        {'name': 'Xbox Series S 1TB ホワイト EP2-00650',                'keywords': ['Xbox Series S 1TB ホワイト', 'Xbox Series S 1TB White', 'EP2-00650']},
        {'name': 'Xbox Series X RRT-00015',                             'keywords': ['Xbox Series X']},
        {'name': 'Xbox Series S 512 GB EP2-10065',                             'keywords': ['Xbox Series S']},
        {'name': 'Meta Quest 3 512GB',                   'keywords': ['Meta Quest 3 512GB', 'Meta Quest 3 512', 'MetaQuest 3 512', 'Quest 3 512GB']},
        {'name': 'Meta Quest 3 128GB',                   'keywords': ['Meta Quest 3 128GB', 'Meta Quest 3 128', 'MetaQuest 3 128', 'Quest 3 128GB']},
        {'name': 'Meta Quest 3S 128GB',                'keywords': ['Meta Quest 3S 128GB', 'Meta Quest 3S 128', 'MetaQuest 3S 128']},
        {'name': 'Meta Quest 3S 256GB',                'keywords': ['Meta Quest 3S 256GB', 'Meta Quest 3S 256', 'MetaQuest 3S 256']},
        {'name': 'Pokemon GO Plus +',                   'keywords': ['Pokemon GO Plus', 'ポケモンGOプラス']},
        {'name': 'Steam Deck 有機EL 1TB',              'keywords': ['Steam Deck 有機EL 1TB', 'Steam Deck OLED 1TB']},
        {'name': 'Steam Deck 有機EL 512GB',            'keywords': ['Steam Deck 有機EL 512', 'Steam Deck OLED 512GB']},
        {'name': 'Nintendo Switch ニンテンドーサウンドクロック Alarmo',                             'keywords': ['Alarmo', 'ニンテンドーサウンドクロック']},
        {'name': 'PS5 ディスクドライブ  CFI-ZDD1J',     'keywords': ['CFI-ZDD1J', 'PS5 ディスクドライブ  CFI']},
        {'name': 'PS5 コントローラー “Spider-Man 2”  CFI-ZCT1JZ2',          'keywords': ['CFI-ZCT1JZ2']},
        {'name': 'PS5 コントローラー 30周年 CFI-ZCT1J30',                'keywords': ['CFI-ZCT1J30']},
        {'name': 'PS5 コントローラー ロボット CFI-ZCT1JZ3',               'keywords': ['CFI-ZCT1JZ3']},
        {'name': 'PS5 コントローラー “FINAL FANTASY”  CFIJ-15500',          'keywords': ['CFIJ-15500']},
        {'name': 'PS5 コントローラー  “ゴッド・オブ・ウォー" CFI-ZCT1JZ1',   'keywords': ['CFI-ZCT1JZ1']},
        {'name': 'PS5 コントローラー フォートナイ CFI-ZCT1JZ4',            'keywords': ['CFI-ZCT1JZ4']},
        {'name': 'PS5 ワイヤレスコントローラー “Ghost of Yotei” ゴールド リミテッドエディション CFI-ZCT1JZ7','keywords': ['CFI-ZCT1JZ7']},
        {'name': 'PS5 ワイヤレスコントローラー “Ghost of Yotei” ブラック リミテッドエディション CFI-ZCT1JZ8','keywords': ['CFI-ZCT1JZ8']},
        {'name': 'PS5 ワイヤレスコントローラー “ゴッド・オブ・ウォー” 20th Anniversary リミテッドエディション CFI-ZCT1JZA','keywords': ['CFI-ZCT1JZA']},
        {'name': 'PS5 コントローラー ミッドナイト ブラック + USBケーブル for PC CFIJ15502','keywords': ['CFIJ15502']},
        {'name': 'PS5 コントローラー “モンスターハンターワイルズ” CFI-ZCT1JZ5','keywords': ['CFI-ZCT1JZ5']},
        {'name': 'PS5 コントローラー “Marathon” リミテッドエディション CFI-ZCT1JZD',               'keywords': ['CFI-ZCT1JZD']},
        {'name': 'PS5 コントローラーアストロボット ジョイフル リミテッドエディション CFI-ZCT1JZC',          'keywords': ['CFI-ZCT1JZC']},
        {'name': 'PS5 ワイヤレスコントローラー “原神” リミテッドエディション CFI-ZCT2JZE',                   'keywords': ['CFI-ZCT2JZE']},
        {'name': 'PS5 コントローラー テクノ レッド CFI-ZCT2J13',           'keywords': ['CFI-ZCT2J13']},
        {'name': 'PS5 コントローラー リミックス グリーン CFI-ZCT2J14',     'keywords': ['CFI-ZCT2J14']},
        {'name': 'PS5 コントローラー リズム ブルー CFI-ZCT2J15',           'keywords': ['CFI-ZCT2J15']},
        {'name': 'PS5 コントローラー クロマ パール CFI-ZCT1J12',           'keywords': ['CFI-ZCT1J12']},
        {'name': 'PS5 コントローラー インディゴ CFI-ZCT1J11',              'keywords': ['CFI-ZCT1J11']},
        {'name': 'PS5 コントローラー クロマ グリーン CFI-ZCT1J10',         'keywords': ['CFI-ZCT1J10']},
        {'name': 'PS5 コントローラー コバルト ブルー CFI-ZCT1J09',         'keywords': ['CFI-ZCT1J09']},
        {'name': 'PS5 コントローラー シルバー CFI-ZCT1J08',                'keywords': ['CFI-ZCT1J08']},
        {'name': 'PS5 コントローラー ヴォルカニック レッド CFI-ZCT1J07',   'keywords': ['CFI-ZCT1J07']},
        {'name': 'PS5 コントローラー グレー カモフラージュ CFI-ZCT1J06',   'keywords': ['CFI-ZCT1J06']},
        {'name': 'PS5 コントローラー ブルー CFI-ZCT1J05',                  'keywords': ['CFI-ZCT1J05']},
        {'name': 'PS5 コントローラー パープル CFI-ZCT1J04',                'keywords': ['CFI-ZCT1J04']},
        {'name': 'PS5\u3000コントローラー ピンク\u3000CFI-ZCT1J03',                  'keywords': ['CFI-ZCT1J03']},
        {'name': 'PS5 コントローラー レッド CFI-ZCT1J02',                  'keywords': ['CFI-ZCT1J02']},
        {'name': 'PS5 コントローラー ブラック CFI-ZCT1J01',                'keywords': ['CFI-ZCT1J01']},
        {'name': 'PS5 コントローラー ホワイト CFI-ZCT1J',                'keywords': ['PS5 コントローラー ホワイト CFI-ZCT1J', 'CFI-ZCT1J ']},
        {'name': 'Nintendo Switch Proコントローラー ゼルダの伝説',             'keywords': ['Proコントローラー ゼルダの伝説', 'Switch Proコントローラー ゼルダ']},
        {'name': 'Nintendo Switch Proコントローラー スプラトゥーン3エディション',            'keywords': ['Proコントローラー スプラトゥーン3', 'スプラトゥーン3エディション']},
        {'name': 'Nintendo Switch Proコントローラー',                    'keywords': ['Nintendo Switch Proコントローラー']},
        {'name': 'Nintendo Switch Joy-Con 2 (L) ライトブルー/(R) ライトレッド',     'keywords': ['Joy-Con 2 (L) ライトブルー/(R) ライトレッド']},
        {'name': 'Nintendo Switch Joy-Con 2 (L) ライトパープル/(R) ライトグリーン', 'keywords': ['Joy-Con 2 (L) ライトパープル/(R) ライトグリーン']},
        {'name': 'Nintendo Switch Joy-Con 2 (L) ライトブルー',          'keywords': ['Joy-Con 2 (L) ライトブルー']},
        {'name': 'Nintendo Switch Joy-Con 2 (R) ライトレッド',          'keywords': ['Joy-Con 2 (R) ライトレッド']},
        {'name': 'Nintendo Switch Joy-Con 2 充電グリップ',            'keywords': ['Joy-Con 2 充電グリップ']},
        {'name': 'Nintendo Switch スーパー マリオパーティ 4人で遊べる Joy-Conセット',           'keywords': ['マリオパーティ 4人で遊べる Joy-Conセット']},
        {'name': 'スーパー マリオパーティ  Joy-Conセット',              'keywords': ['マリオパーティ  Joy-Conセット', 'マリオパーティ Joy-Conセット']},
        {'name': 'Nintendo Switch Joy-Con (L)/(R)  ネオンレッド/ネオンブルー', 'keywords': ['ネオンレッド/ネオンブルー']},
        {'name': 'Nintendo Switch Joy-Con (L)/(R) ネオングリーン/ネオンピンク','keywords': ['ネオングリーン/ネオンピンク']},
        {'name': 'Nintendo Switch Joy-Con(L)/(R)  ネオンブルー/ネオンイエロー','keywords': ['ネオンブルー/ネオンイエロー']},
        {'name': 'Nintendo Switch Joy-Con(L)/(R) ネオンパープル/ネオンオレンジ','keywords': ['ネオンパープル/ネオンオレンジ']},
        {'name': 'Nintendo Switch Joy-Con (L)/(R)パステルパープル/ パステルグリーン','keywords': ['パステルパープル/ パステルグリーン', 'パステルパープル/パステルグリーン']},
        {'name': 'Nintendo Switch Joy-Con (L)/(R)パステルピンク/パステルイエロー','keywords': ['パステルピンク/パステルイエロー']},
        {'name': 'Nintendo Switch Joy-Con (L)/(R) パステルピンク',            'keywords': ['Joy-Con (L)/(R) パステルピンク']},
        {'name': 'Joy-Con (L)/(R)  グレー/グレー',             'keywords': ['Joy-Con (L)/(R)  グレー', 'Joy-Con グレー/グレー']},
        {'name': 'Joy-Con (L)/(R)  ネオンイエロー',            'keywords': ['Joy-Con (L)/(R)  ネオンイエロー', 'Joy-Con (L)/(R) ネオンイエロー']},
        {'name': 'Joy-Con (L)/(R) レッド',                    'keywords': ['Joy-Con (L)/(R) レッド']},
        # ゲームソフト（Switch 2版を先に置き、キーワード優先マッチさせる）
        # PS5専用（Ghost of Yotei 本体バンドルは上のハードウェアセクションに移動済み）
        {'name': '【NS2】Split Fiction',                      'keywords': ['Split Fiction', 'スプリット フィクション']},
        {'name': '【NS1】It Takes Two',                       'keywords': ['It Takes Two', 'イット テイクス トゥー']},
        {'name': '【NS2】プラグマタ',                         'keywords': ['プラグマタ', 'Pragmata']},
        {'name': '【NS2】ゼルダの伝説 ティアーズ オブ ザ キングダム Nintendo Switch 2 Edition', 'jan': '4902370553321', 'keywords': ['ティアーズ オブ ザ キングダム Nintendo Switch 2 Edition', 'Switch 2 ティアーズ オブ ザ キングダム']},
        {'name': '【NS2】スーパー マリオパーティ ジャンボリー Nintendo Switch 2 Edition ＋ ジャンボリーTV', 'jan': '4902370553352', 'keywords': ['マリオパーティ ジャンボリー Nintendo Switch 2 Edition', 'ジャンボリーTV']},
        {'name': '【NS2】スーパーマリオブラザーズ ワンダー Nintendo Switch 2 Edition + みんなでリンリンパーク', 'jan': '4902370554113', 'keywords': ['スーパーマリオブラザーズ ワンダー Nintendo Switch 2 Edition', 'みんなでリンリンパーク']},
        {'name': '【NS2】ゼルダの伝説 ブレス オブ ザ ワイルド Nintendo Switch 2 Edition', 'jan': '4902370553291', 'keywords': ['ブレス オブ ザ ワイルド Nintendo Switch 2 Edition', 'Switch 2 ブレス オブ ザ ワイルド']},
        {'name': '【NS2】ゼノブレイドクロス ディフィニティブエディション Nintendo Switch 2 Edition', 'jan': '4902370554243', 'keywords': ['ゼノブレイドクロス ディフィニティブエディション Nintendo Switch 2 Edition', 'Switch 2 ゼノブレイドクロス']},
        {'name': '【NS2】星のカービィ ディスカバリー Nintendo Switch 2 Edition ＋ スターリーワールド', 'jan': '4902370553383', 'keywords': ['星のカービィ ディスカバリー Nintendo Switch 2 Edition', 'スターリーワールド']},
        {'name': '【NS2】桃太郎電鉄2 ～あなたの町も きっとある～ Nintendo Switch 2 Edition 東日本編＋西日本編/Switch 2', 'jan': '4988602179231', 'keywords': ['桃太郎電鉄2 Nintendo Switch 2 Edition', '桃鉄2 Switch 2']},
        {'name': '【NS2】牧場物語 Lets！風のグランドバザール Nintendo Switch 2 Edition', 'jan': '4535506303950', 'keywords': ['牧場物語 Lets！風のグランドバザール Nintendo Switch 2 Edition', '牧場物語 Switch 2']},
        {'name': '【NS2】あつまれ どうぶつの森 Nintendo Switch 2 Edition', 'jan': '4902370553901', 'keywords': ['あつまれ どうぶつの森 Nintendo Switch 2 Edition', 'あつ森 Switch 2']},
        {'name': '【NS2】ぽこ あ ポケモン', 'jan': '4521329460420', 'keywords': ['ぽこ あ ポケモン', 'ぽこあポケモン']},
        {'name': '【NS2】ゼルダ無双 封印戦記/Switch 2', 'jan': '4988615211102', 'keywords': ['ゼルダ無双 封印戦記', 'ゼルダ無双 Switch 2']},
        {'name': '【NS2】ドンキーコング バナンザ', 'jan': '4902370553413', 'keywords': ['ドンキーコング バナンザ']},
        {'name': '【PS5】仁王3', 'jan': '4988615211331', 'keywords': ['仁王3', 'Nioh 3']},
        {'name': '【NS2】マリオテニス フィーバー', 'jan': '4902370553932', 'keywords': ['マリオテニス フィーバー']},
        {'name': '【NS2】ヨッシーとフカシギの図鑑', 'jan': '4902370554151', 'keywords': ['ヨッシーとフカシギの図鑑']},
        {'name': '【NS2】カービィのエアライダー', 'jan': '4902370553642', 'keywords': ['カービィのエアライダー']},
        {'name': '【PS5】SILENT HILL f', 'jan': '4988602178968', 'keywords': ['SILENT HILL f', 'サイレントヒル f']},
        {'name': '【PS5】黒神話：悟空', 'jan': '4580695760930', 'keywords': ['黒神話：悟空', '黒神話 悟空']},
        {'name': '【PS5】プラグマタ', 'jan': '4976219137799', 'keywords': ['PS5 プラグマタ', 'PS5 Pragmata']},
        {'name': '【NS2】ドラゴンクエストVII Reimagined -Switch', 'jan': '4988601012089', 'keywords': ['ドラゴンクエストVII Reimagined', 'ドラクエ7 Reimagined']},
        {'name': '【PS5】Ghost of Yotei', 'jan': '4948872017305', 'keywords': ['Ghost of Yotei', 'ゴースト オブ ヨウテイ']},
        {'name': '【PS5】アストロボット', 'jan': '4948872017183', 'keywords': ['アストロボット', 'ASTRO BOT']},
        {'name': '【PS5】DEATH STRANDING 2: ON THE BEACH', 'jan': '4948872017213', 'keywords': ['DEATH STRANDING 2', 'デスストランディング2']},
        {'name': '【PS5】Stellar Blade', 'jan': '4948872016858', 'keywords': ['Stellar Blade', 'ステラーブレイド']},
        {'name': '【NS2】REANIMAL', 'jan': '4571574970410', 'keywords': ['REANIMAL']},
        {'name': '【PS5】Alan Wake 2 Deluxe', 'jan': '4595057030064', 'keywords': ['Alan Wake 2 Deluxe', 'Alan Wake 2']},
        {'name': '【NS2】龍が如く０ 誓いの場所 Director’s Cut', 'jan': '4974365870584', 'keywords': ['龍が如く０ 誓いの場所 Director’s Cut', '龍が如く0 Switch 2']},
        {'name': '【PS5】Split Fiction', 'jan': '4938833024749', 'keywords': ['PS5 Split Fiction', 'PS5 スプリット フィクション']},
        {'name': '【PS5】Marvel’s Spider-Man 2', 'jan': '4948872016865', 'keywords': ['Marvel’s Spider-Man 2', 'Spider-Man 2 PS5']},
        {'name': '【PS5】Minecraft', 'jan': '4595057030071', 'keywords': ['PS5 Minecraft', 'PS5 マインクラフト']},
        # Pokemon LEGENDS Z-A（Switch / Switch 2 両対応）
        {'name': '【NS2】Pokemon LEGENDS Z-A Nintendo Switch 2 Edition',           'keywords': ['Switch 2 Pokemon LEGENDS Z-A', 'Switch2 Pokemon LEGENDS Z-A', 'Pokemon LEGENDS Z-A Nintendo Switch 2', 'Switch 2 ポケモン LEGENDS Z-A']},
        {'name': '【NS1】Pokemon LEGENDS Z-A',             'keywords': ['ポケモン LEGENDS Z-A', 'Pokemon LEGENDS Z-A', 'LEGENDS Z-A']},
        # ゼルダ（Switch）
        {'name': '【NS1】ゼルダの伝説\u3000ティアーズ オブ ザ キングダム',   'keywords': ['ティアーズ オブ ザ キングダム', 'Tears of the Kingdom', 'ティアキン']},
        {'name': '【NS1】ゼルダの伝説 知恵のかりもの',                  'keywords': ['知恵のかりもの', 'Echoes of Wisdom']},
        # リングフィット（Switch）
        {'name': 'リングフィット アドベンチャー',           'keywords': ['リングフィット アドベンチャー', 'リングフィット', 'Ring Fit Adventure']},
        # マリオパーティ（Switch）
        {'name': '【NS1】スーパー マリオパーティ ジャンボリー',             'keywords': ['マリオパーティ ジャンボリー', 'Mario Party Jamboree', 'スーパー マリオパーティ ジャンボリー']},
        # ゼノブレイドクロス（Switch 2専用）
        {'name': '【NS1】ゼノブレイドクロス ディフィニティブエディション',            'keywords': ['ゼノブレイドクロス', 'Xenoblade Chronicles X', 'ゼノブレイド クロス']},
        # トモダチコレクション（Switch / Switch 2 両対応）
        {'name': 'トモダチコレクション Switch 2',           'keywords': ['Switch 2 トモダチコレクション', 'Switch2 トモダチコレクション', 'トモダチコレクション Nintendo Switch 2']},
        {'name': '【NS1】トモダチコレクション わくわく生活',             'keywords': ['トモダチコレクション わくわく', 'Tomodachi Collection', 'トモダチコレクション']},
        # モンスターハンターストーリーズ3（Switch / Switch 2 両対応）
        {'name': '【NS2】モンスターハンターストーリーズ3 ～運命の双竜～', 'keywords': ['NS2 モンスターハンターストーリーズ3', 'Switch 2 モンスターハンターストーリーズ3']},
        {'name': '【PS5】モンスターハンターストーリーズ3 ～運命の双竜～',   'keywords': ['モンスターハンターストーリーズ3', 'Monster Hunter Stories 3']},
        # マリオカート ワールド（Switch 2専用）
        {'name': '【NS2】マリオカート ワールド',            'keywords': ['マリオカート ワールド', 'Mario Kart World']},
    ],
    'カメラ': [
        {'name': 'チェキフィルム 2P',                   'keywords': ['instax フィルム 20枚入', 'JP2', 'mini film 2P', 'チェキ フィルム 2パック']},
        {'name': '【mini】FUJIFILM instax フィルム(10枚入) JP1',                   'keywords': ['instax フィルム 10枚入', 'JP1', 'mini film 1P', 'チェキ フィルム 1パック']},
        {'name': '【SQUARE】FUJIFILM instax フィルム(10枚入) WW1',          'keywords': ['WW1', 'SQUARE FUJIFILM instax フィルム(10枚入)']},
        {'name': '【SQUARE】FUJIFILM instax フィルム(20枚入) WW2',          'keywords': ['WW2', 'SQUARE FUJIFILM instax フィルム(20枚入)']},
        {'name': '【WIDE】FUJIFILM instax フィルム(10枚入)',           'keywords': ['WIDE FUJIFILM instax フィルム(10枚入)']},
        {'name': '【WIDE】FUJIFILM instax フィルム(20枚入)',           'keywords': ['WIDE FUJIFILM instax フィルム(20枚入)']},
        {'name': '【WIDE】FUJIFILM instax フィルム(50枚入)',           'keywords': ['WIDE FUJIFILM instax フィルム(50枚入)']},
        {'name': '【mini】 instax フィルム(10枚入) PASTEL GALAXY',  'keywords': ['PASTEL GALAXY']},
        {'name': '写ルンです（新パッケージ）',             'keywords': ['写ルンです', 'Fujifilm Disposable']},
        {'name': 'instax mini 12 チェキ [ピンク]',               'keywords': ['mini 12 チェキ [ピンク]', 'mini 12 ピンク', 'mini 12 Pink']},
        {'name': 'instax mini 13 チェキ [キャンディピンク]',               'keywords': ['キャンディピンク', 'mini 13 チェキ [キャンディピンク]', 'mini 13 ピンク', 'mini 13 Pink']},
        {'name': 'instax mini 13 チェキ [フロストブルー]',               'keywords': ['フロストブルー', 'Frost Blue', 'mini 13 チェキ [フロストブルー]', 'mini 13 ブルー', 'mini 13 Blue']},
        {'name': 'instax mini 13 チェキ [ラグーングリーン]',             'keywords': ['ラグーングリーン', 'ミントグリーン', 'mini 13 チェキ [ラグーングリーン]', 'mini 13 チェキ [ミントグリーン]', 'mini 13 グリーン', 'mini 13 Green']},
        {'name': 'instax mini 13 チェキ [クレイホワイト]',             'keywords': ['クレイホワイト', 'クリーミーホワイト', 'mini 13 チェキ [クレイホワイト]', 'mini 13 チェキ [クリーミーホワイト]', 'mini 13 ホワイト', 'mini 13 White']},
        {'name': 'instax mini 13 チェキ [ドリーミーパープル]',             'keywords': ['ドリーミーパープル', 'mini 13 チェキ [ドリーミーパープル]', 'mini 13 パープル', 'mini 13 Purple']},
        {'name': 'instax mini 40 チェキ',                     'keywords': ['instax mini 40']},
        {'name': 'instax mini 90 チェキ ネオクラシック[ブラック]',                  'keywords': ['ネオクラシック[ブラック]', 'mini 90 ブラック', 'mini 90 Black']},
        {'name': 'instax mini 90 チェキ ネオクラシック [ブラウン]',                  'keywords': ['ネオクラシック [ブラウン]', 'ネオクラシック[ブラウン]', 'mini 90 ブラウン', 'mini 90 Brown']},
        {'name': 'instax mini 99 チェキ',                     'keywords': ['instax mini 99']},
        {'name': 'instax WIDE 400 チェキ [ジェットブラック]',            'keywords': ['ジェットブラック', 'WIDE 400 チェキ [ジェットブラック]', 'WIDE 400 ブラック', 'WIDE400 Black', 'WIDE 400 Black', 'WIDE 400 チェキ [ブラック]']},
        {'name': 'instax WIDE 400 チェキ [グリーン]',            'keywords': ['WIDE 400 グリーン', 'WIDE 400 チェキ [グリーン]', 'WIDE400 Green']},
        {'name': 'instax WIDE 400',                    'keywords': ['WIDE 400 チェキ', 'instax WIDE 400', 'WIDE400']},
        {'name': 'instax mini Evo チェキ USB [ブラック]',                 'keywords': ['Evo チェキ USB [ブラック]', 'mini Evo チェキ USB [ブラック]', 'mini Evo ブラック', 'mini Evo Black']},
        {'name': 'instax mini Evo チェキ USB [ブラウン]',                 'keywords': ['Evo チェキ USB [ブラウン]', 'mini Evo チェキ USB [ブラウン]', 'mini Evo ブラウン', 'mini Evo Brown']},
        {'name': 'instax WIDE Evo',                    'keywords': ['WIDE Evo チェキ', 'instax WIDE Evo']},
        {'name': 'instax mini Evo チェキ USB [ピンク]',               'keywords': ['Evo チェキ USB [ピンク]', 'mini Evo チェキ USB [ピンク]', 'mini Evo ピンク', 'mini Evo PINK']},
        {'name': 'instax mini Evo チェキ USB [ジェントル ローズ]',        'keywords': ['ジェントル ローズ', 'Evo チェキ USB [ジェントル ローズ]', 'GENTLE ROSE', 'ジェントルローズ']},
        {'name': 'instax mini Evo Cinema',             'keywords': ['mini Evo Cinema', 'Evo シネマ']},
        {'name': 'instax SQUARE SQ40 ブラック',         'keywords': ['SQ40 チェキスクエア', 'SQ40 ブラック', 'SQ40 Black']},
        {'name': 'instax SQUARE SQ1 [ブルー]',           'keywords': ['SQ1 [ブルー]', 'SQ1 ブルー', 'SQ1 Blue']},
        {'name': 'instax SQUARE SQ1 [オレンジ]',         'keywords': ['SQ1 [オレンジ]', 'SQ1 オレンジ', 'SQ1 Orange']},
        {'name': 'instax SQUARE SQ1 [ホワイト]',         'keywords': ['SQ1 [ホワイト]', 'SQ1 ホワイト', 'SQ1 White']},
        {'name': 'CANON PowerShot IXY 650 m [シルバー]\u300025年',                 'keywords': ['IXY 650 m [シルバー]', 'IXY 650 m シルバー', '650 m [シルバー]']},
        {'name': 'CANON PowerShot IXY 650 m [ブラック] 25年',                 'keywords': ['IXY 650 m [ブラック]', 'IXY 650 m ブラック', '650 m [ブラック]']},
        {'name': '◆デジタルカメラ IXY 650 [シルバー]',                   'keywords': ['IXY 650 [シルバー]', 'IXY 650 シルバー']},
        {'name': '◆デジタルカメラ IXY 650 [ブラック]',                   'keywords': ['IXY 650 [ブラック]', 'IXY 650 ブラック']},
        {'name': '◆Canon PowerShot SX740 HS [シルバー]',                     'keywords': ['SX740 HS [シルバー]', 'SX740 シルバー', 'SX740 Silver']},
        {'name': '◆PowerShot SX740 HS [ブラック]',                     'keywords': ['SX740 HS [ブラック]', 'SX740 ブラック', 'SX740 Black']},
        {'name': 'CANON PowerShot SX70 HS',                               'keywords': ['SX70', 'PowerShot SX70']},
        {'name': 'Canon PowerShot V10 [ブラック] トライポッドグリップキット',                      'keywords': ['PowerShot V10', 'Canon V10']},
        {'name': 'CANON PowerShot V1',                       'keywords': ['PowerShot V1 ', 'Canon V1 ']},
        {'name': 'CANON PowerShot G7 X Mark III PowerShot 30th Anniversary Edition',      'keywords': ['30th Anniversary Edition', 'G7 X Mark III 30th']},
        {'name': '◆PowerShot G7 X Mark III\u3000SV',             'keywords': ['G7 X Mark III　SV', 'G7 X Mark III SV', 'Mark III シルバー']},
        {'name': 'PowerShot G7 X Mark III\u3000B',              'keywords': ['G7 X Mark III　B', 'G7 X Mark III B', 'Mark III ブラック', 'G7 X Mark III']},
        {'name': 'Canon PowerShot G7 X MarkII',                       'keywords': ['G7 X MarkII', 'G7X Mark2', 'PowerShot G7 X Mark II']},
        {'name': 'デジタルカメラ PowerShot G1 X Mark III',            'keywords': ['G1 X Mark III', 'PowerShot G1 X']},
        {'name': '◆デジタルカメラ PowerShot G5 X Mark II',           'jan': '4549292119114', 'keywords': ['PowerShot G5 X Mark II', 'G5 X Mark II']},
        {'name': 'PowerShot V10 [ホワイト]',                          'jan': '4549292243567', 'keywords': ['PowerShot V10 ホワイト', 'PowerShot V10 [ホワイト]']},
        {'name': 'Canon PowerShot V10 [シルバー]',                    'jan': '4549292212532', 'keywords': ['PowerShot V10 シルバー', 'PowerShot V10 [シルバー]']},
        {'name': 'CANON PowerShot V10 [ブラック]',                    'jan': '4549292212556', 'keywords': ['PowerShot V10 ブラック', 'PowerShot V10 [ブラック]']},
        {'name': 'FUJIFILM X100VI Silver 【新型2025】 E/J',               'keywords': ['X100VI Silver', 'X100VI Silver 【新型']},
        {'name': 'FUJIFILM X100VI Black 【新型2025】 E/J',               'keywords': ['X100VI Black', 'X100VI Black 【新型']},
        {'name': 'FUJIFILM X100VI [シルバー]',               'keywords': ['X100VI [シルバー]', 'fujifilm x100vi [シルバー]']},
        {'name': 'FUJIFILM X100VI [ブラック]',               'keywords': ['X100VI [ブラック]']},
        {'name': 'FUJIFILM X100V [シルバー]',                 'jan': '4547410423419', 'keywords': ['X100V シルバー', 'X100V [シルバー]']},
        {'name': 'FUJIFILM X100V [ブラック]',                 'jan': '4547410423433', 'keywords': ['X100V ブラック', 'X100V [ブラック]']},
        {'name': 'FUJIFILM X-E5 ボディ [ブラック]',            'jan': '4547410559064', 'keywords': ['X-E5 ボディ ブラック', 'X-E5 [ブラック]']},
        {'name': 'FUJIFILM X-E5 ボディ [シルバー]',            'jan': '4547410559118', 'keywords': ['X-E5 ボディ シルバー', 'X-E5 [シルバー]']},
        {'name': 'FUJIFILM X-M5 ボディ [シルバー]',            'jan': '4547410555165', 'keywords': ['X-M5 ボディ シルバー', 'X-M5 [シルバー]']},
        {'name': 'FUJIFILM X-M5 ボディ [ブラック]',            'jan': '4547410555158', 'keywords': ['X-M5 ボディ ブラック', 'X-M5 [ブラック]']},
        {'name': 'FUJIFILM X-T30 II XC15-45mmレンズキット',                  'keywords': ['X-T30', 'Fujifilm X-T30 Lens Kit']},
        {'name': 'Panasonic LUMIX DC-TZ99-K [ブラック]',             'keywords': ['LUMIX TZ99 Black', 'DC-TZ99-K', 'TZ99 ブラック']},
        {'name': 'LUMIX DC-TZ99 ホワイト',             'keywords': ['LUMIX TZ99 White', 'DC-TZ99-W', 'TZ99 ホワイト']},
        {'name': 'RICOH GR IV Monochrome',             'keywords': ['GR IV Monochrome', 'GR4 Monochrome']},
        {'name': 'RICOH GR IV Black',                        'keywords': ['RICOH GR IV', 'GR4', 'GR IV']},
        {'name': 'RICOH GR IV HDF',                          'jan': '4549212311871', 'keywords': ['GR IV HDF', 'GR4 HDF']},
        {'name': 'RICOH GR IIIx HDF 特別モデル',              'jan': '4549212306297', 'keywords': ['GR IIIx HDF', 'GR3x HDF']},
        {'name': 'RICOH GR III HDF 特別モデル',               'jan': '4549212306181', 'keywords': ['GR III HDF', 'GR3 HDF']},
        {'name': 'RICOH GR III Street Edition',               'jan': '4549212302763', 'keywords': ['GR III Street Edition', 'GR3 Street']},
        {'name': 'RICOH GR IIIx Urban Edition',        'keywords': ['GR IIIx Urban', 'GR3x Urban']},
        {'name': 'RICOH GR III Diary Edition',         'keywords': ['GR III Diary', 'GR3 Diary']},
        {'name': '◆RICOH GR IIIx',                     'keywords': ['RICOH GR IIIx', 'GR3x', 'GR IIIx']},
        {'name': '◆RICOH GR III',                       'keywords': ['RICOH GR III', 'GR3', 'GR III']},
        {'name': 'Nikon Z50II ダブルズームキット',        'keywords': ['Z50II ダブルズーム', 'Z50II Double Zoom']},
        {'name': 'Z50II 18-140 VR レンズキット',        'keywords': ['Z50II 18-140']},
        {'name': 'Z50II 16-50 VR レンズキット',        'keywords': ['Z50II 16-50']},
        {'name': 'Nikon Z50II ボディ',                 'keywords': ['Nikon Z50II', 'Z50II', 'Z50 II']},
        {'name': 'Nikon Z5II ボディ',                  'jan': '4960759917157', 'keywords': ['Nikon Z5II ボディ', 'Z5II ボディ']},
        {'name': 'Nikon Z6III ボディ',                 'jan': '4960759916181', 'keywords': ['Nikon Z6III ボディ', 'Z6III ボディ']},
        {'name': 'デジタルカメラ サイバーショット DSC-RX100M7G シューティンググリップキット', 'jan': '4548736106390', 'keywords': ['DSC-RX100M7G', 'RX100M7G']},
        {'name': '◆DSC-RX100M7',                       'jan': '4548736106284', 'keywords': ['DSC-RX100M7', 'RX100M7']},
        {'name': 'SONY DSC-RX100M6',                    'jan': '4548736083264', 'keywords': ['DSC-RX100M6', 'RX100M6']},
        {'name': 'SONY サイバーショット DSC-RX100M5A',  'jan': '4548736086449', 'keywords': ['DSC-RX100M5A', 'RX100M5A']},
        # タムロン レンズ
        {'name': 'TAMRON 18-300mm F/3.5-6.3 Di III-A VC VXD (B061) ニコンZ用',             'keywords': ['B061) ニコンZ用', 'B061 ニコンZ', 'タムロン 18-300 ニコン']},
        {'name': 'TAMRON 18-300mm F/3.5-6.3 Di III-A VC VXD (B061) [フジフイルム用]',                'keywords': ['B061) [フジフイルム用]', 'タムロン 18-300 フジ']},
        {'name': '◇TAMRON 18-300mm F/3.5-6.3 Di III-A VC VXD (B061) [ソニーE用]',             'keywords': ['B061) [ソニーE用]', 'タムロン 18-300 ソニー', 'TAMRON 18-300mm F/3.5-6.3']},
        {'name': 'TAMRON 28-75mm F/2.8 Di III VXD G2 (A063) [ニコンZ用]',           'keywords': ['A063) [ニコンZ用]', 'A063 ニコンZ', 'TAMRON 28-75 ニコン']},
        {'name': 'TAMRON 28-75mm F/2.8 Di III VXD G2 (A063S)',           'keywords': ['A063S', 'TAMRON 28-75mm F/2.8']},
        {'name': 'TAMRON 28-300mm F/4-7.1 Di III VC VXD (A074)',                     'keywords': ['A074', 'TAMRON 28-300']},
        {'name': 'TAMRON 28-200mm F/2.8-5.6 Di III RXD (A071)',                     'keywords': ['A071', 'TAMRON 28-200']},
        {'name': 'TAMRON 25-200mm F/2.8-5.6 Di III VXD G2 (A075)',                     'keywords': ['A079', 'TAMRON 25-200', 'タムロン 25-200']},
        # その他レンズ・カメラ
        {'name': 'Nikon NIKKOR Z DX 50-250F4.5-6.3 VR',              'keywords': ['NIKKOR Z DX 50-250', 'Z DX 50-250']},
        {'name': 'OLYMPUS PEN E-P7 EZダブルズームキット [シルバー]',                'keywords': ['PEN E-P7', 'OM SYSTEM E-P7', 'E-P7']},
        {'name': 'Sigma 28-70mm F2.8',                'keywords': ['SIGMA 28-70', 'シグマ 28-70']},
    ],
    'ポケカ': [
        {'name': '【MEGA】 ニンジャスピナー BOX',      'keywords': ['ニンジャスピナー', 'Ninja Spinner']},
        {'name': '【MEGA】 ムニキスゼロ BOX',          'keywords': ['ムニキスゼロ']},
        {'name': '【MEGA】 MEGAドリームex BOX',        'keywords': ['MEGAドリーム', 'Mega Dream ex']},
        {'name': '【MEGA】 インフェルノX BOX',         'keywords': ['インフェルノX', 'Inferno X']},
        {'name': '【MEGA】 メガブレイブ BOX',          'keywords': ['メガブレイブ', 'Mega Brave']},
        {'name': '【MEGA】メガシンフォニア BOX',      'keywords': ['メガシンフォニア', 'Mega Sinfonia']},
        {'name': '【MEGA】 アビスアイ BOX',            'jan': '4521329462127', 'keywords': ['アビスアイ', 'Abyss Eye']},
        {'name': '【S＆V】ブラックボルト BOX',        'keywords': ['ブラックボルト', 'Black Bolt']},
        {'name': '【S＆V】ホワイトフレア BOX',        'keywords': ['ホワイトフレア', 'White Flare']},
        {'name': '【S＆V】ブラックボルト デラックス BOX', 'jan': '4521329427300', 'keywords': ['ブラックボルト デラックス', 'ブラックボルトDX', 'ブラックボルト Deluxe']},
        {'name': '【S＆V】ホワイトフレア デラックス BOX', 'jan': '4521329427324', 'keywords': ['ホワイトフレア デラックス', 'ホワイトフレアDX', 'ホワイトフレア Deluxe']},
        {'name': 'ポケモンセンター スペシャルBOX ヒロシマ', 'jan': '4521329427669', 'keywords': ['スペシャルBOX ヒロシマ', 'ポケモンセンター ヒロシマ']},
        {'name': 'ポケモンセンター スペシャルBOX フクオカ', 'jan': '4521329431536', 'keywords': ['スペシャルBOX フクオカ', 'ポケモンセンター フクオカ']},
        {'name': 'ポケモンセンター スペシャルBOX トウホク', 'jan': '4521329431277', 'keywords': ['スペシャルBOX トウホク', 'ポケモンセンター トウホク']},
        {'name': '【S＆V】ロケット団の栄光 BOX',      'keywords': ['ロケット団の栄光', 'Team Rocket Glory']},
        {'name': '【S＆V】熱風のアリーナ BOX',        'keywords': ['熱風のアリーナ']},
        {'name': '【S＆V】バトルパートナーズ BOX',    'keywords': ['バトルパートナーズ', 'Battle Partners']},
        {'name': '【S＆V】テラスタルフェスex BOX',    'keywords': ['テラスタルフェス', 'Terastal Fes']},
        {'name': '【S＆V】超電ブレイカー BOX',        'keywords': ['超電ブレイカー', 'Surging Sparks']},
        {'name': '【S＆V】楽園ドラゴーナ BOX',        'keywords': ['楽園ドラゴーナ', 'Paradise Dragona']},
        {'name': '【S＆V】ステラミラクル BOX',        'keywords': ['ステラミラクル', 'Stellar Miracle']},
        {'name': '【S＆V】ナイトワンダラー BOX',      'keywords': ['ナイトワンダラー', 'Night Wanderer']},
        {'name': '【S＆V】変幻の仮面 BOX',            'keywords': ['変幻の仮面', 'Twilight Masquerade']},
        {'name': '【S＆V】クリムゾンヘイズ BOX',      'keywords': ['クリムゾンヘイズ', 'Crimson Haze']},
        {'name': '【S＆V】ワイルドフォース BOX',      'keywords': ['ワイルドフォース', 'Wild Force']},
        {'name': '【S＆V】サイバージャッジ BOX',      'keywords': ['サイバージャッジ', 'Cyber Judge']},
        {'name': '【S＆V】シャイニートレジャーex BOX','keywords': ['シャイニートレジャー', 'Shiny Treasure']},
        {'name': '【S＆V】古代の咆哮 BOX',            'keywords': ['古代の咆哮', 'Ancient Roar']},
        {'name': '【S＆V】未来の一閃 BOX',            'keywords': ['未来の一閃', 'Future Flash']},
        {'name': '【S＆V】レイジングサーフ BOX',      'keywords': ['レイジングサーフ', 'Raging Surf']},
        {'name': '【S＆V】黒炎の支配者\u3000BOX',          'keywords': ['黒炎の支配者', 'Obsidian Flames']},
        {'name': '【S＆V】ポケモンカード151 BOX',     'keywords': ['ポケモンカード151', 'Pokemon 151']},
        {'name': '【S＆S】VSTARユニバース BOX',       'keywords': ['VSTARユニバース', 'VSTAR Universe']},
        {'name': '【S＆V】クレイバースト BOX',        'keywords': ['クレイバースト', 'Paldea Evolved']},
        {'name': '【S＆V】スノーハザード BOX',        'keywords': ['スノーハザード', 'Snow Hazard']},
        {'name': '【S＆V】トリプレットビート BOX',    'keywords': ['トリプレットビート', 'Triplet Beat']},
        {'name': '【S＆V】スカーレットex BOX',        'keywords': ['スカーレットex', 'Scarlet ex']},
        {'name': '【S＆V】バイオレットex BOX',        'keywords': ['バイオレットex', 'Violet ex']},
    ],
    'ワンピ': [
        {'name': '【OP-10】 王族の血統',      'keywords': ['OP-10', '王族の血統', 'Royal Blood']},
        {'name': '【OP-11】 神速の拳',        'keywords': ['OP-11', '神速の拳']},
        {'name': '【OP-12】 師弟の絆',        'keywords': ['OP-12', '師弟の絆']},
        {'name': '【OP-13】 受け継がれる意志', 'keywords': ['OP-13', '受け継がれる意志']},
        {'name': '【OP-14】 蒼海の七傑',      'keywords': ['OP-14', '蒼海の七傑']},
        {'name': '【OP-15】 神の島の冒険',    'keywords': ['OP-15', '神の島の冒険']},
        {'name': '【EB-03】 ONE PIECE Heroines Edition', 'keywords': ['EB-03', 'Heroines Edition']},
        {'name': '【EB-04】 EGGHEAD CRISIS',   'keywords': ['EB-04', 'EGGHEAD CRISIS']},
        {'name': '【PRB-01】 THE BEST',        'keywords': ['PRB-01']},
        {'name': '【PRB-02】 THE BEST vol.2',  'keywords': ['PRB-02', 'THE BEST vol.2']},
    ],
    'スマートフォン': [
        # iPhone 17 Pro Max（色別 × 容量別）
        {'name': 'iPhone 17 Pro Max 256GB シルバー',         'keywords': ['iPhone 17 Pro Max 256GB シルバー', 'iPhone 17 Pro Max 256 Silver', 'Pro Max 256 シルバー']},
        {'name': 'iPhone 17 Pro Max 256GB ディープブルー',   'keywords': ['iPhone 17 Pro Max 256GB ディープブルー', 'iPhone 17 Pro Max 256 Blue', 'Pro Max 256 ディープブルー', 'Pro Max 256 Deep Blue']},
        {'name': 'iPhone 17 Pro Max 256GB コズミックオレンジ','keywords': ['iPhone 17 Pro Max 256GB コズミックオレンジ', 'iPhone 17 Pro Max 256 Orange', 'Pro Max 256 コズミックオレンジ', 'Pro Max 256 Cosmic Orange']},
        {'name': 'iPhone 17 Pro Max 512GB シルバー',         'keywords': ['iPhone 17 Pro Max 512GB シルバー', 'iPhone 17 Pro Max 512 Silver', 'Pro Max 512 シルバー']},
        {'name': 'iPhone 17 Pro Max 512GB ディープブルー',   'keywords': ['iPhone 17 Pro Max 512GB ディープブルー', 'iPhone 17 Pro Max 512 Blue', 'Pro Max 512 ディープブルー', 'Pro Max 512 Deep Blue']},
        {'name': 'iPhone 17 Pro Max 512GB コズミックオレンジ','keywords': ['iPhone 17 Pro Max 512GB コズミックオレンジ', 'iPhone 17 Pro Max 512 Orange', 'Pro Max 512 コズミックオレンジ', 'Pro Max 512 Cosmic Orange']},
        {'name': 'iPhone 17 Pro Max 1TB シルバー',           'keywords': ['iPhone 17 Pro Max 1TB シルバー', 'iPhone 17 Pro Max 1TB Silver', 'Pro Max 1TB シルバー']},
        {'name': 'iPhone 17 Pro Max 1TB ディープブルー',     'keywords': ['iPhone 17 Pro Max 1TB ディープブルー', 'iPhone 17 Pro Max 1TB Blue', 'Pro Max 1TB ディープブルー', 'Pro Max 1TB Deep Blue']},
        {'name': 'iPhone 17 Pro Max 1TB コズミックオレンジ', 'keywords': ['iPhone 17 Pro Max 1TB コズミックオレンジ', 'iPhone 17 Pro Max 1TB Orange', 'Pro Max 1TB コズミックオレンジ', 'Pro Max 1TB Cosmic Orange']},
        {'name': 'iPhone 17 Pro Max 2TB シルバー',           'keywords': ['iPhone 17 Pro Max 2TB シルバー', 'iPhone 17 Pro Max 2TB Silver', 'Pro Max 2TB シルバー']},
        {'name': 'iPhone 17 Pro Max 2TB ディープブルー',     'keywords': ['iPhone 17 Pro Max 2TB ディープブルー', 'iPhone 17 Pro Max 2TB Blue', 'Pro Max 2TB ディープブルー', 'Pro Max 2TB Deep Blue']},
        {'name': 'iPhone 17 Pro Max 2TB コズミックオレンジ', 'keywords': ['iPhone 17 Pro Max 2TB コズミックオレンジ', 'iPhone 17 Pro Max 2TB Orange', 'Pro Max 2TB コズミックオレンジ', 'Pro Max 2TB Cosmic Orange']},
        # iPhone 17 Pro（色別 × 容量別）
        {'name': 'iPhone 17 Pro 256GB シルバー',             'keywords': ['iPhone 17 Pro 256GB シルバー', 'iPhone 17 Pro 256 Silver', 'Pro 256 シルバー']},
        {'name': 'iPhone 17 Pro 256GB ディープブルー',       'keywords': ['iPhone 17 Pro 256GB ディープブルー', 'iPhone 17 Pro 256 Blue', 'Pro 256 ディープブルー', 'Pro 256 Deep Blue']},
        {'name': 'iPhone 17 Pro 256GB コズミックオレンジ',   'keywords': ['iPhone 17 Pro 256GB コズミックオレンジ', 'iPhone 17 Pro 256 Orange', 'Pro 256 コズミックオレンジ', 'Pro 256 Cosmic Orange']},
        {'name': 'iPhone 17 Pro 512GB シルバー',             'keywords': ['iPhone 17 Pro 512GB シルバー', 'iPhone 17 Pro 512 Silver', 'Pro 512 シルバー']},
        {'name': 'iPhone 17 Pro 512GB ディープブルー',       'keywords': ['iPhone 17 Pro 512GB ディープブルー', 'iPhone 17 Pro 512 Blue', 'Pro 512 ディープブルー', 'Pro 512 Deep Blue']},
        {'name': 'iPhone 17 Pro 512GB コズミックオレンジ',   'keywords': ['iPhone 17 Pro 512GB コズミックオレンジ', 'iPhone 17 Pro 512 Orange', 'Pro 512 コズミックオレンジ', 'Pro 512 Cosmic Orange']},
        {'name': 'iPhone 17 Pro 1TB シルバー',               'keywords': ['iPhone 17 Pro 1TB シルバー', 'iPhone 17 Pro 1TB Silver', 'Pro 1TB シルバー']},
        {'name': 'iPhone 17 Pro 1TB ディープブルー',         'keywords': ['iPhone 17 Pro 1TB ディープブルー', 'iPhone 17 Pro 1TB Blue', 'Pro 1TB ディープブルー', 'Pro 1TB Deep Blue']},
        {'name': 'iPhone 17 Pro 1TB コズミックオレンジ',     'keywords': ['iPhone 17 Pro 1TB コズミックオレンジ', 'iPhone 17 Pro 1TB Orange', 'Pro 1TB コズミックオレンジ', 'Pro 1TB Cosmic Orange']},
    ],
    'その他': [
        {'name': 'バンダイ たまごっちパラダイスTamagotchi Paradise - Purple Sky', 'keywords': ['Paradise - Purple Sky', 'Tamagotchi Paradise Purple']},
        {'name': 'バンダイ たまごっちパラダイスTamagotchi Paradise - Blue Water',  'keywords': ['Paradise - Blue Water', 'Tamagotchi Paradise Blue']},
        {'name': 'バンダイ たまごっちパラダイスTamagotchi Paradise - Pink Land',   'keywords': ['Paradise - Pink Land', 'Tamagotchi Paradise Pink']},
        {'name': 'バンダイ たまごっちパラダイスTamagotchi Paradise - Jade Forest', 'keywords': ['Paradise - Jade Forest', 'Tamagotchi Paradise Jade']},
    ],
}

# フラットなリスト（全商品）
ALL_PRODUCTS = []
for category, items in PRODUCTS.items():
    for item in items:
        ALL_PRODUCTS.append({**item, 'category': category})

# 商品名のセット（重複除去用）
PRODUCT_NAMES = {p['name'] for p in ALL_PRODUCTS}
